### ISSUE TITLE
Two constants and client parameters with the same name in validation swager

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#100]
```
  constants:
  - !<!ConstantSchema> &ref_23
    type: constant
    value: !<!ConstantValue> 
      value: 1.0.0
      language:
        default:
          name: ''
          description: ''
    valueType: *ref_0
    language: !<!Languages> 
      default:
        name: ApiVersion-1.0.0
        description: Api Version (1.0.0)
    protocol: !<!Protocols> {}
  - *ref_4
  - *ref_5
  - *ref_6
  - *ref_7
  - *ref_8
  - *ref_9
  - !<!ConstantSchema> &ref_26
    type: constant
    value: !<!ConstantValue> 
      value: 1.0.0
      language:
        default:
          name: ''
          description: ''
    valueType: *ref_0
    language: !<!Languages> 
      default:
        name: ApiVersion-1.0.0
        description: Api Version (1.0.0)
    protocol: !<!Protocols> {}
```

```
 - !<!Parameter> 
        schema: *ref_23
        implementation: Client
        required: true
        language: !<!Languages> 
          default:
            name: ApiVersion
            description: Api Version
            serializedName: apiVersion
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
            in: query
```

```
 - !<!Parameter> 
        schema: *ref_26
        implementation: Client
        required: true
        language: !<!Languages> 
          default:
            name: ApiVersion
            description: Api Version
            serializedName: apiVersion
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
            in: query
```
