### ISSUE TITLE
Running storage blob produces code-model with null enum value

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#108]
# Configuration

``` yaml
title: Storage.Blobs
require:
- $(this-folder)/../readme.samples.md
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/swagger/readme.md
namespace: Azure.Storage.Blobs
```
# Code model

``` yaml
 - !<!Property> 
                schema: !<!SealedChoiceSchema> &ref_77
                  choices:
                  - !<!ChoiceValue> 
                    value: null
                    language:
                      default:
                        name: none
                        description: ''
                  - !<!ChoiceValue> 
                    value: container
                    language:
                      default:
                        name: blobContainer
                        description: ''
                  - !<!ChoiceValue> 
                    value: blob
                    language:
                      default:
                        name: blob
                        description: ''
                  type: sealed-choice
                  apiVersions:
                  - !<!ApiVersion> 
                    version: '2019-02-02'
                  choiceType: *ref_6
                  language: !<!Languages> 
                    default:
                      name: PublicAccessType
                      description: MISSING·SCHEMA-DESCRIPTION-CHOICE
                      header: x-ms-blob-public-access
                  protocol: !<!Protocols> {}
```
