### ISSUE TITLE
containerName parameter missing when processing storage blob 

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#109]
# Configuration

``` yaml
title: Storage.Blobs
require:
- $(this-folder)/../readme.samples.md
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/swagger/readme.md
namespace: Azure.Storage.Blobs
```

# Code model
``` yaml
- !<!Parameter> &ref_142
  schema: *ref_6
  implementation: Client
  required: true
  extensions:
    x-az-trace: true
    x-ms-priority: 0
    x-ms-skip-url-encoding: true
  language: !<!Languages> 
    default:
      name: url
      description: 'The URL of the service account, container, or blob that is the targe of the desired operation.'
      serializedName: url
  protocol: !<!Protocols> 
    http: !<!HttpParameter> 
      in: uri

- !<!Parameter> &ref_146
  schema: *ref_13
  implementation: Client
  required: true
  extensions:
    x-ms-priority: 1
  language: !<!Languages> 
    default:
      name: x-ms-version
      description: Specifies the version of the operation to use for this request.
      serializedName: x-ms-version
  protocol: !<!Protocols> 
    http: !<!HttpParameter> 
      in: header

  request: !<!Request> 
      parameters:
      - *ref_142
      - !<!Parameter> 
        schema: *ref_196
        implementation: Method
        required: true
        language: !<!Languages> 
          default:
            name: comp
            description: MISSING·PARAMETER-DESCRIPTION
            serializedName: comp
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
            in: query
      - !<!Parameter> 
        schema: *ref_145
        implementation: Method
        language: !<!Languages> 
          default:
            name: timeout
            description: >-
              The timeout parameter is expressed in seconds. For more information, see <a href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations">Setting Timeouts for Blob
              Service Operations.</a>
            serializedName: timeout
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
            in: query
      - *ref_146
      - !<!Parameter> 
        schema: *ref_13
        implementation: Method
        language: !<!Languages> 
          default:
            name: x-ms-client-request-id
            description: 'Provides a client-generated, opaque value with a 1 KB character limit that is recorded in the analytics logs when storage analytics logging is enabled.'
            serializedName: x-ms-client-request-id
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
            in: header
      language: !<!Languages> 
        default:
          name: ''
          description: ''
      protocol: !<!Protocols> 
        http: !<!HttpRequest> 
          path: '/{containerName}/{blob}'
          method: put
          uri: '{url}'
```
