### ISSUE TITLE
x-ms-discriminator-value

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#12]
Information should be available in `language.default.discriminator_value` and solved (whatever present in Swagger or not)

**Comment by fearthecowboy** [comment]
Full discriminator information is in the model now.

- `ObjectSchema` has an optional `discriminatorValue`  property
- A parent class will have an optional `discriminator` property that has a reference to the discriminator property and dictionaries for `all` children (recursively) and for `immediate` children (for just the direct subclasses) -- key is the `discriminatorValue` value is a reference to the ObjectSchema

example:  https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/outputs/body-complex/code-model-v4.yaml#L1459

``` yaml
    discriminator: !<!Discriminator> 
      all:
        cookiecuttershark: *ref_13
        goblin: *ref_12
        salmon: *ref_7
        sawshark: *ref_11
        shark: *ref_10
        smart_salmon: *ref_9
      immediate:
        salmon: *ref_7
        shark: *ref_10
      property: *ref_6
```
