### ISSUE TITLE
edge case, "object" parameter with no properties will get flattened to nothing

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#142]
**Describe the issue**

Edge case, an "object" parameter with no properties will get flattened to nothing.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json#L3977

"template" parameter is just an "object", with no properties.

After flatten:

```
      - schema: *ref_222
        flattened: true
        implementation: Method
        required: true
        extensions:
          x-ms-requestBody-name: template
        language:
          default:
            name: template
            description: The template provided to calculate hash.
        protocol:
          http:
            in: body
            style: json
      language:
        default:
          name: ''
          description: ''
      protocol:
        http:
          path: /providers/Microsoft.Resources/calculateTemplateHash
          method: post
          knownMediaType: json
          mediaTypes:
          - application/json
          uri: '{$host}'
```

---

This is found by accident. We did not set `payload-flattening-threshold`, and did not expect this json get flattened at all.

README.tmp.md is simply referring to this single json file (I escaped the ``` within):

```
# Resource
> see https://aka.ms/autorest
This is the AutoRest configuration file for Resource.
---
\``` yaml $(java)
input-file:
- Microsoft.Resources/stable/2019-08-01/resources.json
\```
```

It seems picking up the `payload-flattening-threshold` configure from a nearby README.java.md file. (Yes, we are working on Java extension)

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/readme.java.md

Would like to have a confirmation on the `payload-flattening-threshold` configure when called on markdown. Thanks.

** REQUIRED ** 
**ModelerFour** version: 4.4.158
**AutoRest-core** version: 3.0.6198
**CommandLine** : `payload-flattening-threshold=1`
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json
