### ISSUE TITLE
Some issues with 4.4.165 naming

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#147]
Pascal case changes
- [ ] i.e. CMYKColors is CmykColors
- [x] FirstParameterGroup in AzureParameterGrouping is now first-parameter-group
- [ ] LROsOperations operation group in Lro is now LrOSOperations (couple more cases in Lro folder, ie LROSADsOperations is now LrosaDsOperations)
- [ ] Client name for AutoRestLongRunningOperationTest (LRO) is now AutoRestLong-runningOperationTest

Snakecase changes
- [ ] property and parameter custom_header is now customHeader (from AzureParameterGrouping)
- [ ] foo_client_request_id from HeaderCustomNamedRequestIdParamGroupingParameters in AzureSpecialProperties is now foo-client-request-id
- [ ] subscription_id global parameter in AzureSpecial Properties is now subscriptionId
- [ ] xms_client_request_id is now x_ms_client_request_id in AzureSpecials
- [ ] get_path_valid in AzureSpecials skip_url_encoding_operations is now get_path_path_valid
- [ ] unencoded_path_param in get_swagger_path_valid (AzureSpecials) is now unencodedPathParam
- [ ] regenerate_key in regenerate_key (StorageManagementClient) is now regenerateKey (grouped parameters don't seem to be converted)

**Comment by iscai-msft** [comment]
Here's my configuration:
naming:
    parameter: snakecase
    property: snakecase
    operation: snakecase
    operationGroup:  pascalcase
    choice:  pascalcase
    choiceValue:  uppercase
    constant:  uppercase
    type:  pascalcase

**Comment by fearthecowboy** [comment]
Ah, yes, missed the groups collection and the non-signature parameters. 

The CMYK => Cmyk issue.... I dunno what the best solution for that is. If we start making a whitelist of acronyms, we're gonna get to a point where a given usage may not be an acronym.

But, I'm going to add configuration for a set of overrides, and we can experiment with that.

**Comment by fearthecowboy** [comment]
the next build supports:

``` yaml
modelerfour:
  # customization of the identifier normalization and naming provided by the prenamer.
  # pascal|pascalcase - MultiWordIdentifier 
  # camel|camelcase - multiWordIdentifier 
  # snake|snakecase - multi_word_identifier
  # upper|uppercase - MULTI_WORD_IDENTIFIER 
  # kebab|kebabcase - multi-word-identifier 
  # space|spacecase - spaces between recognized words
  # default is the first one in the list below:
  naming: 
    parameter: camel # camel|pascal|snake|upper|kebab|space
    property: camel # camel|pascal|snake|upper|kebab|space
    operation: pascal # pascal|camel|snake|upper|kebab|space
    operationGroup:  pascal # pascal|camel|snake|upper|kebab|space
    choice:  pascal # pascal|camel|snake|upper|kebab|space
    choiceValue:  pascal # pascal|camel|snake|upper|kebab|space
    constant:  pascal # pascal|camel|snake|upper|kebab|space
    type:  pascal # pascal|camel|snake|upper|kebab|space
    override:  # a key/value mapping of names to force to a certain value 
      cmyk : CMYK
      $host: $host
```

if you need a certain word overridden, add it to `override` -- or you can use `space` case for that category and then completely handle the name format yourself  (split the string on spaces)
