### ISSUE TITLE
Parameter name mismatch

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#152]
There is a mismatch in parameter name and it's definition in the uri. .net generator matching is case sensitive and this was a breaking change for us.

```
- !<!Parameter> &ref_95
  schema: *ref_7
  implementation: Client
  required: true
  extensions:
    x-in: path
    x-ms-priority: 0
    x-ms-skip-url-encoding: true
>>>>>    x-name: Endpoint
    x-required: true
    x-type: string
  language: !<!Languages> 
    default:
>>>>>      name: endpoint
      description: 'Supported Cognitive Services endpoints (protocol and hostname, for example: https://westus.api.cognitive.microsoft.com).'
      serializedName: Endpoint
  protocol: !<!Protocols> 
    http: !<!HttpParameter> 
      in: uri
```

```
    request: !<!Request> 
      parameters:
      - *ref_95
      - !<!Parameter> &ref_106
        schema: *ref_96
        implementation: Method
        language: !<!Languages> 
          default:
            name: modelVersion
            description: '(Optional) This value indicates which model will be used for scoring. If a model-version is not specified, the API should default to the latest, non-preview version. '
            serializedName: model-version
        protocol: !<!Protocols> 
          http: !<!HttpParameter> 
            in: query
 
..........
      protocol: !<!Protocols> 
        http: !<!HttpWithBodyRequest> 
          path: /entities/linking
          method: post
          knownMediaType: json
          mediaTypes:
          - application/json
          - text/json
>>>>      uri: '{Endpoint}/text/analytics/v3.0-preview.1'
```
