### ISSUE TITLE
Running TextAnalytics through latest modeler results in two types with the same name

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#153]
![image](https://user-images.githubusercontent.com/1697911/73868611-a0e6ce00-47fd-11ea-8fde-c6398c158f0d.png)

`DocumentSentiment-sentiment` enum got renamed to `DocumentSentiment`

while there is an object type named `DocumentSentiment` already

**Comment by fearthecowboy** [comment]
Interesting collision. 

Did you literally call the generated Enum type `DocumentSentimentSentiment' ?

**Comment by fearthecowboy** [comment]
What would a good name for the enum be if there is a collision? `DocumentSentimentEnum` ?

**Comment by pakrym** [comment]
> Did you literally call the generated Enum type `DocumentSentimentSentiment' ?

Yes, while I'm sure it's not the name final library would ship with I would like initial generation result to be at least buildable.

> What would a good name for the enum be if there is a collision? DocumentSentimentEnum ?

`DocumentSentimentEnum` sounds good

**Comment by fearthecowboy** [comment]
added some name disambiguation in modelerfour `4.6.186`+ -- in some cases, `x-ms-client-name` would be required, but in this case it should rename the enum.

**Comment by pakrym** [comment]
Still there now with a new type:
``` yaml
elementType: !<!ObjectSchema> &ref_4
          type: object
          apiVersions:
          - !<!ApiVersion> 
            version: V3.0-Preview.1
          properties:
          - !<!Property> 
            schema: !<!StringSchema> &ref_67
              type: string
              apiVersions:
              - !<!ApiVersion> 
                version: V3.0-Preview.1
              language: !<!Languages> 
                default:
                  name: DocumentErrorId
                  description: Document Id.
              protocol: !<!Protocols> {}
            required: true
            serializedName: id
            language: !<!Languages> 
              default:
                name: id
                description: Document Id.
            protocol: !<!Protocols> {}
          - !<!Property> 
            schema: !<!ObjectSchema> &ref_5
              type: object
              apiVersions:
              - !<!ApiVersion> 
                version: V3.0-Preview.1
              language: !<!Languages> 
                default:
                  name: DocumentError
                  description: Document Error.
                  namespace: ApiV30Preview1
              protocol: !<!Protocols> {}
            required: true
            serializedName: error
            language: !<!Languages> 
              default:
                name: error
                description: Document Error.
            protocol: !<!Protocols> {}
          language: !<!Languages> 
            default:
              name: DocumentError
              description: ''
              namespace: ApiV30Preview1
          protocol: !<!Protocols> {}
```
