### ISSUE TITLE
FATAL error when generating mgmt-plane web service

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#159]
**Describe the issue**

FATAL error when generating mgmt-plane web service:
```
FATAL: YAMLException: bad indentation of a sequence entry in "code-model-v4.yaml" at line 40766, column 25:
                            value: auditlogs
                            ^
```

Interactive screenshot 
![interactive](https://user-images.githubusercontent.com/53292327/74024076-0395c080-49dc-11ea-86d1-4c2941f3f00b.jpg)

YAML
[(421)+code-model-v4.yaml.txt](https://github.com/Azure/autorest.modelerfour/files/4170370/421.%2Bcode-model-v4.yaml.txt)

```
                    - type: ServiceIncident
                      endTime: '2017-11-06T22:21:48Z'
                      message: Your application process was restarted as application environment variables changed. This can most likely occur due to update in app settings or swap operation. This event occurred multiple times during the day.
                      metaData:
                      - - name: feature
                        value: auditlogs
                      - name: displayedName
                        value: Check Audit Logs
                      priority: 0
                      solutions: []
```

** REQUIRED ** 
**ModelerFour** version:4.5.176
**AutoRest-core** version:3.0.6207
**CommandLine** :`--java --payload-flattening-threshold=1`
OpenAPI/Swagger file:
[readme.md.temp.txt](https://github.com/Azure/autorest.modelerfour/files/4170357/readme.md.temp.txt)
