### ISSUE TITLE
M4 models differently two client parameter

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#174]
Here:
https://github.com/Azure/azure-rest-api-specs/blob/62b1b41dd4637c3667943aa5b845f08e81671437/specification/synapse/data-plane/Microsoft.Synapse/preview/2019-11-01-preview/sparkFrontend.json#L1435-L1454

```json
    "LivyApiVersionInPath": {
      "name": "livyApiVersion",
      "in": "path",
      "description": "Valid api-version for the request.",
      "required": true,
      "type": "string",
      "default": "2019-11-01-preview",
      "x-ms-skip-url-encoding": true,
      "x-ms-parameter-location": "client"
    },
    "SynapseDnsSuffixInPath": {
      "name": "SynapseDnsSuffix",
      "in": "path",
      "required": true,
      "type": "string",
      "default": "azuresynapse.net​",
      "x-ms-skip-url-encoding": true,
      "description": "Gets the DNS suffix used as the base for all Synapse service requests.",
      "x-ms-parameter-location": "client"
    }
```

m4 models 
```yaml
globalParameters:
- &ref_201
  schema: *ref_15
  clientDefaultValue: azuresynapse.net​
  implementation: Client
  required: true
  extensions:
    x-in: path
    x-ms-priority: 1
    x-ms-skip-url-encoding: true
    x-name: SynapseDnsSuffix
    x-required: true
    x-type: string
  language:
    default:
      name: synapse_dns_suffix
      description: Gets the DNS suffix used as the base for all Synapse service requests.
      serializedName: SynapseDnsSuffix
  protocol:
    http:
      in: uri
- &ref_228
  schema: *ref_199
  implementation: Client
  required: true
  extensions:
    x-ms-priority: 2
    x-ms-skip-url-encoding: true
  language:
    default:
      name: livy_api_version
      description: Valid api-version for the request.
      serializedName: livyApiVersion
  protocol:
    http:
      in: path
```

I'm confused why the first one has "clientDefaultValue", with a generic string schema, where the second one has no "clientDefaultValue", but a specific schema with a "defaultValue"
