### ISSUE TITLE
content_type parameter should have implementation: Method

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#177]
```
      - &ref_5
        schema: *ref_3
        language:
          default:
            name: content_type
            description: Upload file type
        protocol: {}
```
