### ISSUE TITLE
Naming Convention is not applied to SubscriptionId and flattened parameters

### ISSUE THREAD

**Issue by RodgeFu** [Azure/autorest.modelerfour#195]
**Describe the issue**
Seems naming convention is not applied to subscriptionId in GlobalParameter and flattened parameters

** REQUIRED ** 
**ModelerFour** version: 4.6.200
**AutoRest-core** version: 3.0.6212 
**CommandLine** :
```
autorest --version:3.0.6212 ^
--use=@autorest/modelerfour@4.6.200 ^
--output-folder=c:\t\generated\mm\ ^
--output-artifact=code-model-v4-no-tags ^
--debug ^
c:\git\azure-rest-api-specs\specification\managedNetwork\resource-manager\readme.md
```
OpenAPI/Swagger file:
following extra config added in readme:

# configuration

See documentation [here](doc/00-overview.md)

``` yaml

modelerfour:
    group-parameters: true
    flatten-models: true
    flatten-payloads: true
    # standardize to snake in modelerfour for selecting and formatting in clicommon
    # further naming will be done in clicommon to corresonding convention
    naming: 
        parameter: 'snake'
        operation: 'snake'
        operationGroup:  'snake'
        property: 'snake'
        type:  'snake'
        choice:  'snake'
        choiceValue:  'snake'
        constant:  'snake'
        client: 'pascal'
        override:  # a key/value mapping of names to force to a certain value 
          cmyk : CMYK
          $host: $host
          LRO: LRO

directive:
  - from: swagger-document
    where: $..parameters[?(@.in=='body')]
    transform: >
      $['x-ms-client-flatten'] = true;
    reason: Flatten everything for Azure CLI

```
checking the output yaml file, you can find:
1. subscriptionId is not using snake format while api-version is:
![image](https://user-images.githubusercontent.com/6038235/75600652-cc06c980-5aec-11ea-8697-e807cf0c5406.png)
2. the name of flattened body parameter is not applied the snake naming convention:
![image](https://user-images.githubusercontent.com/6038235/75600664-f0fb3c80-5aec-11ea-986e-e7bff5b8b282.png)
