### ISSUE TITLE
[QUERY] Is there any different on constant schema from modelAsString true/false

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#206]
**Describe the issue**

It appears that modelerfour will generate same constant schema regardless of modelAsString option.

However SDK might need to have different handling based on modelAsString. SDK is required to allow service adding new enum without upgrade, if modelAsString=true.

```
  - &ref_26
    type: constant
    apiVersions:
    - version: '2019-08-01'
    value:
      value: Small
    valueType: *ref_0
    language:
      default:
        name: ConnectorOffer
        description: The cassandra connector offer type for the Cosmos DB C* database account.
    protocol: {}
```

** REQUIRED ** 
**ModelerFour** version: 4.9.236
**AutoRest-core** version: 3.0.6237
**CommandLine** :
OpenAPI/Swagger file: https://github.com/azure/azure-rest-api-specs/blob/1c3a60403422ca8c73df7eb7c65ae2a3c90bf152/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2019-08-01/cosmos-db.json#L7033
