### ISSUE TITLE
Generating multiple schemas with same name

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.modelerfour#216]
**Describe the issue**
There's multiple `DataLakeStorageError` classes when generating azure-storage-blob.
** REQUIRED ** 
**ModelerFour** version: 4.10.246
**AutoRest-core** version: 3.0.6258
**CommandLine** : autorest ../azure-sdk-for-python/sdk/storage/azure-storage-blob/swagger/README.md --use=. --output-artifact=code-model-v4-no-tags
OpenAPI/Swagger file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/storage-dataplane-preview/specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-07-07/blob.json

![image](https://user-images.githubusercontent.com/43154838/76804838-ab5c9600-67b3-11ea-8eb7-a9b50282dda0.png)

**Comment by fearthecowboy** [comment]
You'll have to fix the swagger.  The name guesser can't make a good name for the unnamed inner type.

Add a `x-ms-client-name` to the inner definition 

``` yaml
"DataLakeStorageError": {
      "type": "object",
      "properties": {
         # it's guessing the name for this type should be DataLakeStorageErrorError, 
         # but deduplicates Error so it collides. 
        "error": {
          "x-ms-client-name" : "ErrorDetails",  # add this line to give it a real name.
          "description": "The service error response object.",
          "properties": {
        "Code": {
              "description": "The service error code.",
          "type": "string"
        },
        "Message": {
              "description": "The service error message.",
          "type": "string"
            }
          }
        }
      }
    },
```
