### ISSUE TITLE
int32 enum transformed to number

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#222]
**Describe the issue**
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-03-01/managedClusters.json#L1372-L1386

"count" enum defined as
```
          "type": "integer",
          "format": "int32",
```

I assume it should produce
```
    type: integer
    precision: 32
```
in yaml.

However I got number instead.
```
  - &ref_1
    type: number
    defaultValue: 1
    precision: 32
    language:
      default:
        name: Number
        description: 'Number of masters (VMs) in the container service cluster. Allowed values are 1, 3, and 5. The default value is 1.'
    protocol: {}
```

** REQUIRED ** 
**ModelerFour** version: 4.10.250
**AutoRest-core** version: 3.0.6246
**CommandLine** :
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2020-03-01/managedClusters.json
