### ISSUE TITLE
Usage is not correctly detected for AccessPolicyEntry in keyvault management swagger

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#249]
Note how `AccessPolicyEntry` is input/output but it's property `Permissions` is input only.

```
            elementType: !<!ObjectSchema> &ref_34
              type: object
              apiVersions:
              - !<!ApiVersion> 
                version: '2019-09-01'
              properties:
              - !<!Property> 
                schema: *ref_7
                required: true
                serializedName: tenantId
                language: !<!Languages> 
                  default:
                    name: tenantId
                    description: The Azure Active Directory tenant ID that should be used for authenticating requests to the key vault.
                protocol: !<!Protocols> {}
              - !<!Property> 
                schema: *ref_8
                required: true
                serializedName: objectId
                language: !<!Languages> 
                  default:
                    name: objectId
                    description: 'The object ID of a user, service principal or security group in the Azure Active Directory tenant for the vault. The object ID must be unique for the list of access policies.'
                protocol: !<!Protocols> {}
              - !<!Property> 
                schema: *ref_9
                required: false
                serializedName: applicationId
                language: !<!Languages> 
                  default:
                    name: applicationId
                    description: ' Application ID of the client making request on behalf of a principal'
                protocol: !<!Protocols> {}
              - !<!Property> 
                schema: !<!ObjectSchema> &ref_35
                  type: object
                  apiVersions:
                  - !<!ApiVersion> 
                    version: '2019-09-01'
                  properties:
                  - !<!Property> 
                    schema: !<!ArraySchema> &ref_105
                      type: array
                      apiVersions:
                      - !<!ApiVersion> 
                        version: '2019-09-01'
                      elementType: *ref_10
                      language: !<!Languages> 
                        default:
                          name: PermissionsKeys
                          description: Permissions to keys
                      protocol: !<!Protocols> {}
                    serializedName: keys
                    language: !<!Languages> 
                      default:
                        name: keys
                        description: Permissions to keys
                    protocol: !<!Protocols> {}
                  - !<!Property> 
                    schema: !<!ArraySchema> &ref_106
                      type: array
                      apiVersions:
                      - !<!ApiVersion> 
                        version: '2019-09-01'
                      elementType: *ref_11
                      language: !<!Languages> 
                        default:
                          name: PermissionsSecrets
                          description: Permissions to secrets
                      protocol: !<!Protocols> {}
                    serializedName: secrets
                    language: !<!Languages> 
                      default:
                        name: secrets
                        description: Permissions to secrets
                    protocol: !<!Protocols> {}
                  - !<!Property> 
                    schema: !<!ArraySchema> &ref_107
                      type: array
                      apiVersions:
                      - !<!ApiVersion> 
                        version: '2019-09-01'
                      elementType: *ref_12
                      language: !<!Languages> 
                        default:
                          name: PermissionsCertificates
                          description: Permissions to certificates
                      protocol: !<!Protocols> {}
                    serializedName: certificates
                    language: !<!Languages> 
                      default:
                        name: certificates
                        description: Permissions to certificates
                    protocol: !<!Protocols> {}
                  - !<!Property> 
                    schema: !<!ArraySchema> &ref_108
                      type: array
                      apiVersions:
                      - !<!ApiVersion> 
                        version: '2019-09-01'
                      elementType: *ref_13
                      language: !<!Languages> 
                        default:
                          name: PermissionsStorage
                          description: Permissions to storage accounts
                      protocol: !<!Protocols> {}
                    serializedName: storage
                    language: !<!Languages> 
                      default:
                        name: storage
                        description: Permissions to storage accounts
                    protocol: !<!Protocols> {}
                  serializationFormats:
                  - json
                  usage:
                  - input
                  language: !<!Languages> 
                    default:
                      name: Permissions
                      description: 'Permissions the identity has for keys, secrets, certificates and storage.'
                      namespace: ''
                  protocol: !<!Protocols> {}
                required: true
                serializedName: permissions
                language: !<!Languages> 
                  default:
                    name: permissions
                    description: 'Permissions the identity has for keys, secrets and certificates.'
                protocol: !<!Protocols> {}
              serializationFormats:
              - json
              usage:
              - input
              - output
              language: !<!Languages> 
                default:
                  name: AccessPolicyEntry
                  description: An identity that have access to the key vault. All identities in the array must use the same tenant ID as the key vault's tenant ID.
                  namespace: ''
              protocol: !<!Protocols> {}
```
