### ISSUE TITLE
Content-type parameter SealedChoiceSchema ChoiceType not set.

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#256]
```
 - !<!SealedChoiceSchema> &ref_119
    choices:
    - !<!ChoiceValue> 
      value: application/pdf
      language:
        default:
          name: ApplicationPdf
          description: Content Type 'application/pdf'
    - !<!ChoiceValue> 
      value: image/jpeg
      language:
        default:
          name: ImageJpeg
          description: Content Type 'image/jpeg'
    - !<!ChoiceValue> 
      value: image/png
      language:
        default:
          name: ImagePng
          description: Content Type 'image/png'
    - !<!ChoiceValue> 
      value: image/tiff
      language:
        default:
          name: ImageTiff
          description: Content Type 'image/tiff'
    type: sealed-choice
    language: !<!Languages> 
      default:
        name: ContentType
        description: Content type for upload
    protocol: !<!Protocols> {}  
```
