### ISSUE TITLE
Duplicated parent references

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#257]
https://github.com/Azure/azure-rest-api-specs/blob/49fc16354df7211f8392c56884a3437138317d1f/specification/timeseriesinsights/resource-manager/readme.md

```
  - !<!ObjectSchema> &ref_104
    type: object
    apiVersions:
    - !<!ApiVersion> 
      version: 2018-08-15-preview
    children: !<!Relations> 
      all:
      - !<!ObjectSchema> &ref_105
        type: object
        apiVersions:
        - !<!ApiVersion> 
          version: 2018-08-15-preview
        parents: !<!Relations> 
          all:
          - *ref_104
          - !<!ObjectSchema> &ref_108
            ...
          - *ref_104
          - *ref_108
```
