### ISSUE TITLE
M4 should remove transitive parents from immediate parents collection in multiple inheritance 

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#258]
Azure/azure-rest-api-specs:specification/timeseriesinsights/resource-manager/readme.md@49fc163

For example in this case *ref_107 already inherits from *ref_108

```
 - !<!ObjectSchema> &ref_107
                type: object
                apiVersions:
                - !<!ApiVersion> 
                  version: 2018-08-15-preview
                
                parents: !<!Relations> 
                  all:
                  - *ref_108
                  immediate:
                  - *ref_108
```

But StandardEnvironmentResourceProperties lists both of them as immediate parents instead of only listing `ref_107` and `ref_109`

```
 - !<!ObjectSchema> &ref_106
                    type: object
                    apiVersions:
                    - !<!ApiVersion> 
                      version: 2018-08-15-preview
                    parents: !<!Relations> 
                      all:
                      ...
                      - *ref_107
                      - *ref_108
                      - *ref_109
                      - *ref_107
                      - *ref_108
                      - *ref_108
                      - *ref_109
                      - *ref_107
                      - *ref_108
                      immediate:
                      - *ref_109
                      - *ref_107
                      - *ref_108
                    serializationFormats:
                    - json
                    usage:
                    - input
                    - output
                    extensions:
                      x-ms-flattened: true
                    language: !<!Languages> 
                      default:
                        name: StandardEnvironmentResourceProperties
                        description: Properties of the standard environment.
                        namespace: ''

```
