### ISSUE TITLE
Parameter with no property (but having parent schema with 3 properties) get flattened to nothing

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#291]
**Describe the issue**
Parameter `NotebookWorkspaceCreateUpdateParameters` is schema with no property (but it has a parent schema `ARMProxyResource`, with 3 properties) get flattened to nothing.
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2019-08-01/notebook.json#L363

Output of m4 (see `flattened: true`)
```
          - parameters:
              - schema: *ref_2
                flattened: true
                implementation: Method
                required: true
                language:
                  default:
                    name: notebookCreateUpdateParameters
                    description: The notebook workspace to create for the current database account.
                protocol:
                  http:
                    in: body
                    style: json
```

Maybe we should not flatten a parameter of schema having parent schema?

** REQUIRED ** 
**ModelerFour** version: 4.13.351
**AutoRest-core** version: 3.0.6282
**CommandLine** : ` autorest --input-file=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2019-08-01/notebook.json --payload-flattening-threshold=1`
OpenAPI/Swagger file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2019-08-01/notebook.json

**Comment by weidongxu-microsoft** [comment]
Might related to https://github.com/Azure/autorest.modelerfour/issues/295

**Comment by weidongxu-microsoft** [comment]
Hello @daviwil, would you take a quick look and let us know what might be the problem?

Issue https://github.com/Azure/autorest.modelerfour/issues/295 is particularly problematic, since the compiler would let the wrong code pass, and we could not know what went wrong.

**Comment by daviwil** [comment]
Are you using the latest `modelerfour` (`--use=@autorest/modelerfour@4.14.362`)?  The snippet you pasted says the parameter's schema is `ref_2`, here's what I see for that schema in my output:

```
                  - !<!ObjectSchema> &ref_2
                    type: object
                    apiVersions:
                      - !<!ApiVersion> 
                        version: '2019-08-01'
                    children: !<!Relations> 
                      all:
                        - *ref_1
                        - !<!ObjectSchema> &ref_3
                          type: object
                          apiVersions:
                            - !<!ApiVersion> 
                              version: '2019-08-01'
                          parents: !<!Relations> 
                            all:
                              - *ref_2
                            immediate:
                              - *ref_2
                          serializationFormats:
                            - json
                          usage:
                            - output
                            - input
                          language: !<!Languages> 
                            default:
                              name: NotebookWorkspaceCreateUpdateParameters
                              description: Parameters to create a notebook workspace resource
                              namespace: ''
                          protocol: !<!Protocols> {}
                      immediate:
                        - *ref_1
                        - *ref_3
                    properties:
                      - !<!Property> 
                        schema: *ref_4
                        readOnly: true
                        serializedName: id
                        language: !<!Languages> 
                          default:
                            name: id
                            description: The unique resource identifier of the database account.
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_5
                        readOnly: true
                        serializedName: name
                        language: !<!Languages> 
                          default:
                            name: name
                            description: The name of the database account.
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_6
                        readOnly: true
                        serializedName: type
                        language: !<!Languages> 
                          default:
                            name: type
                            description: The type of Azure resource.
                        protocol: !<!Protocols> {}
                    serializationFormats:
                      - json
                    usage:
                      - input
                      - output
                    extensions:
                      x-ms-azure-resource: true
                    language: !<!Languages> 
                      default:
                        name: ARMProxyResource
                        description: The resource model definition for a ARM proxy resource. It will have everything other than required location and tags
                        namespace: ''
                    protocol: !<!Protocols> {}
                immediate:
                  - *ref_2
```

What does "flattened to nothing" mean for you?  To me it looks like the parameter uses the schema as-is with no flattening.  What output would you expect to see in this case?
