### ISSUE TITLE
Property schema using parent type instead of correct child type

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.modelerfour#295]
**Describe the issue**
The part of swagger specifies that property `osDiskImage` is type `GalleryOSDiskImage`
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json#L1810-L1834

However after m4, it is now its parent type `GalleryDiskImage`.

```
                    - schema: &ref_355
                        type: object
                        apiVersions:
                          - version: '2019-07-01'
                        children:
                          all:
                            - &ref_357
                              type: object
                              apiVersions:
                                - version: '2019-07-01'
                              parents:
                                all:
                                  - *ref_355
                                immediate:
                                  - *ref_355
                              properties:
                                - schema: *ref_356
                                  required: true
                                  serializedName: lun
                                  language:
                                    default:
                                      name: lun
                                      description: >-
                                        This property specifies the logical unit number of the data disk. This value is used to identify data disks within the Virtual Machine and therefore must be unique for each data disk attached to the
                                        Virtual Machine.
                                  protocol: {}
                              serializationFormats:
                                - json
                              usage:
                                - input
                                - output
                              language:
                                default:
                                  name: GalleryDataDiskImage
                                  description: This is the data disk image.
                                  namespace: ''
                              protocol: {}
                            - &ref_358
                              type: object
                              apiVersions:
                                - version: '2019-07-01'
                              parents:
                                all:
                                  - *ref_355
                                immediate:
                                  - *ref_355
                              serializationFormats:
                                - json
                              usage:
                                - input
                                - output
                              language:
                                default:
                                  name: GalleryOSDiskImage
                                  description: This is the OS disk image.
                                  namespace: ''
                              protocol: {}
                          immediate:
                            - *ref_357
                            - *ref_358
                        properties:
                          - schema: *ref_359
                            readOnly: true
                            serializedName: sizeInGB
                            language:
                              default:
                                name: sizeInGB
                                description: This property indicates the size of the VHD to be created.
                            protocol: {}
                          - schema: *ref_360
                            serializedName: hostCaching
                            language:
                              default:
                                name: hostCaching
                                description: 'The host caching of the disk. Valid values are ''None'', ''ReadOnly'', and ''ReadWrite'''
                            protocol: {}
                          - schema: *ref_361
                            serializedName: source
                            language:
                              default:
                                name: source
                                description: The gallery artifact version source.
                            protocol: {}
                        serializationFormats:
                          - json
                        usage:
                          - input
                          - output
                        language:
                          default:
                            name: GalleryDiskImage
                            description: This is the disk image base class.
                            namespace: ''
                        protocol: {}
                      serializedName: osDiskImage
                      language:
                        default:
                          name: osDiskImage
                          description: This is the disk image base class.
                      protocol: {}
```

** REQUIRED ** 
**ModelerFour** version: 4.13.351
**AutoRest-core** version: 3.0.6282
**CommandLine**:
OpenAPI/Swagger file: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/gallery.json
