### ISSUE TITLE
Response header name is applied to a shared string schema

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#321]
# Swagger

```
{
  "swagger": "2.0",
  "info": {
    "title": "AutoRest Parameter Flattening",
    "description": "Resource Flattening for AutoRest",
    "version": "1.0.0"
  },
  "host": "localhost:3000",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "consumes": [
    "application/json"
  ],
  "paths": {
    "/originalOperation/{originalPathParameter}": {
      "patch": {
        "operationId": "originalOperation",
        "x-ms-client-name": "RenamedOperation",
        "parameters": [
          {
            "name": "originalPathParameter",
            "in": "path",
            "required": true,
            "type": "string",
            "x-ms-client-name": "RenamedPathParameter"
          },
          {
            "name": "originalQueryParameter",
            "x-ms-client-name": "RenamedQueryParameter",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "originalBodyParameter",
            "x-ms-client-name": "RenamedBodyParameter",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/OriginalSchema"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/OriginalSchema"
            },
            "headers": {
              "originalHeader": {
                  "x-ms-client-name": "RenamedHeader",
                  "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "OriginalSchema": {
      "type":  "object",
      "properties": {
        "originalProperty": {
          "type": "object",
          "title": "A set of tags.",
          "x-ms-client-name": "RenamedProperty",
          "description": "A description about the set of tags.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "originalPropertyString": {
          "type": "string",
          "title": "A set of tags.",
          "x-ms-client-name": "RenamedPropertyString",
          "description": "A description about the set of tags."
        }
      },
      "x-ms-client-name": "RenamedSchema",
      "required": [
        "tags"
      ]
    }
  }
}

```

### Code model

```
    - !<!StringSchema> &ref_1
      type: string
      apiVersions:
        - !<!ApiVersion> 
          version: 1.0.0
      language: !<!Languages> 
        default:
          name: RenamedHeader <-----------------
          description: ''
          header: originalHeader <-----------------


  dictionaries:
    - !<!DictionarySchema> &ref_2
      type: dictionary
      elementType: *ref_1 <-----------------
      language: !<!Languages> 
        default:
          name: RenamedProperty
          description: A description about the set of tags.
      protocol: !<!Protocols> {}


parameters:
          - *ref_4
          - !<!Parameter> &ref_8
            schema: *ref_1 <-----------------
            implementation: Method
            required: true
            language: !<!Languages> 
              default:
                name: renamedPathParameter
                description: ''
                serializedName: originalPathParameter
            protocol: !<!Protocols> 
              http: !<!HttpParameter> 
                in: path
          - !<!Parameter> &ref_9
            schema: *ref_1 <-----------------
            implementation: Method
            required: true
            language: !<!Languages> 
              default:
                name: renamedQueryParameter
                description: ''
                serializedName: originalQueryParameter
            protocol: !<!Protocols> 
              http: !<!HttpParameter> 
                in: query
```
