### ISSUE TITLE
api-version processing changes based on header vs query

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#339]
``` json
 "parameters": {
        "ApiVersionParameter": {
            "in": "query",
            "name": "api-version",
            "description": "Version of API to invoke",
            "required": true,
            "type": "string"
        },
}
```
Results in:
```yml
 - !<!Parameter> &ref_126
    schema: *ref_123
    implementation: Client
    origin: 'modelerfour:synthesized/api-version'
    required: true
    language: !<!Languages> 
      default:
        name: apiVersion
        description: Api Version
        serializedName: api-version
    protocol: !<!Protocols> 
      http: !<!HttpParameter> 
        in: query
    - !<!ConstantSchema> &ref_123
      type: constant
      value: !<!ConstantValue> 
        value: 2020-07-20-preview1
      valueType: *ref_1
      language: !<!Languages> 
        default:
          name: ApiVersion20200720Preview1
          description: Api Version (2020-07-20-preview1)
      protocol: !<!Protocols> {}
```
But 
``` json
 "parameters": {
        "ApiVersionParameter": {
            "in": "header",
            "name": "api-version",
            "description": "Version of API to invoke",
            "required": true,
            "type": "string"
        },
}
```

Results in:
```yml
 - !<!Parameter> &ref_125
    schema: *ref_123
    implementation: Client
    required: true
    extensions:
      x-ms-priority: 0
    language: !<!Languages> 
      default:
        name: ApiVersion
        description: Version of API to invoke
        serializedName: api-version

 - !<!StringSchema> &ref_123
      type: string
      apiVersions:
        - !<!ApiVersion> 
          version: 2020-07-20-preview1
      language: !<!Languages> 
        default:
          name: String
          description: ''
      protocol: !<!Protocols> {}

```
