### ISSUE TITLE
x-ms-enum: name is ignored in some cases

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#35]
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/header.json#L981-L992

creates the schema:
```yaml
    $key: paths·header-response-prim-enum·post·responses·200·headers·value·schema
    choices:
    - value: White
      language:
        default:
          name: White
          description: ''
    - value: black
      language:
        default:
          name: black
          description: ''
    - value: GREY
      language:
        default:
          name: GREY
          description: ''
    type: sealed-choice
    description: MISSING-SCHEMA-DESCRIPTION-CHOICE
    apiVersions:
    -
      version: 1.0.0
    choiceType: &ref_3
      $key: string
      type: string
      description: ''
      language:
        default:
          name: string
          description: ''
      protocol: {}
    language:
      default:
        name: paths·header-response-prim-enum·post·responses·200·headers·value·schema
        description: MISSING-SCHEMA-DESCRIPTION-CHOICE
        header: value
    protocol: {}
```

where there was a x-ms-enum to name it "GreyscaleColors"
