### ISSUE TITLE
Modeler should provide a name for anymonymous enum

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#44]
Like these twos:
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/body-array.json#L860-L875

https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/body-array.json#L841-L848

**Comment by fearthecowboy** [comment]
I'm going to add a new plugin stage to give 'better' default names to things that don't have good names.

**Comment by fearthecowboy** [comment]
I have added a 'pre-namer' step into modeler four
 
if you want to get the default (full) experience from the remodeler with all the steps that I put in
you can change the configuration so that your first plugin just has input: modelerfour/identity and you'll get the full experience. 
 
ie( in your plugin configuration, remove  ) 
``` yaml
  # "Shake the tree", and normalize the model
  modelerfour:
    input: openapi-document/multi-api/identity     # the plugin where we get inputs from
 
  # allow developer to do transformations on the code model.
  modelerfour/new-transform:
    input: modelerfour

  mapper:
    input: modelerfour/new-transform      # the plugin where we get inputs from
    output-artifact: python-files
```
 
and replace it with
``` yaml
  mapper:  # < -- your first plugin 
    input: modelerfour/identity
    output-artifact: python-files

```
