### ISSUE TITLE
x-ms-skip-url-encoding not present in model

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#61]
See
https://github.com/Azure/autorest.testserver/blob/0b1e8a2a65915c225851333c2eebe1ff57a3e606/swagger/custom-baseUrl.json#L12-L21

YAML
```yaml
- &ref_3
  schema: *ref_2
  implementation: Client
  required: true
  language:
    default:
      name: accountName
      description: Account Name
  protocol:
    http:
      in: uri
```
