### ISSUE TITLE
x-ms-enum: modelAsString: true generates type: sealed-choice

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.modelerfour#62]
Spec: https://github.com/Azure/autorest.testserver/blob/master/swagger/body-complex.json#L1507
Generates: 
```yaml
            - schema: &ref_59
                choices:
                - value: pink
                  language:
                    default:
                      name: pink
                      description: ''
                - value: gray
                  language:
                    default:
                      name: gray
                      description: ''
                - value: brown
                  language:
                    default:
                      name: brown
                      description: ''
                type: sealed-choice
```

in 4.1.60.
