### ISSUE TITLE
Body parameter incorrectly declared as required

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#64]
Swagger:
https://github.com/Azure/autorest.testserver/blob/aa6ff52dcd43bf2dfcfe92bbb7c9e67eb2a35ff9/swagger/body-string.json#L42-L49

Modeler:
```yaml
      - schema: *ref_6
        implementation: Method
        required: true
        extensions:
          x-ms-requestBody-name: stringBody
        language:
          default:
            name: stringBody
            description: ''
        protocol:
          http:
            in: body
            style: json
```

Impact test `string_putNull`

Modeler version: 4.1.60
