### ISSUE TITLE
Date constants are converted to strings by modeler

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#70]
https://github.com/Azure/autorest.testserver/blob/master/swagger/url.json

```
  - !<!ConstantSchema> &ref_40
    type: constant
    value: !<!ConstantValue> 
      value: '2012-01-01'
      language:
        default:
          name: ''
          description: ''
    valueType: *ref_1
    language: !<!Languages> 
      default:
        name: Constant14
        description: MISSING·SCHEMA-DESCRIPTION-CHOICE
    protocol: !<!Protocols> {}
  - !<!ConstantSchema> &ref_42
    type: constant
    value: !<!ConstantValue> 
      value: '2012-01-01T01:01:01Z'
      language:
        default:
          name: ''
          description: ''
    valueType: *ref_1
    language: !<!Languages> 
      default:
        name: Constant15
        description: MISSING·SCHEMA-DESCRIPTION-CHOICE
    protocol: !<!Protocols> {}
```
```
choiceType: !<!StringSchema> &ref_1
      type: string
      language: !<!Languages> 
        default:
          name: string
          description: simple string
```
