### ISSUE TITLE
Get a "operation" link in "x-ms-pageable"

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#85]
Right now we have that:
```yaml
      x-ms-pageable:
        itemName: values
        nextLinkName: nextLink
        operationName: Paging_getPagesPartialUrlNext
```
Would be nice if we can get an additional node "operation" that is an actual YAML link to the operation, to avoid too much loop to find it.
