### ISSUE TITLE
x-ms-parameterized-host

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#9]
Support in new modeler.

Considering multi-api, assuming all Swaggers have the same `x-ms-parameterized-host` definition, the parameters and the definition of `x-ms-parameterized-host` should be available at the root of the YAML too to simplify generation

**Comment by fearthecowboy** [comment]
Every operation has a `.protocol.http.servers`  which has the parameterized host information.

There is also a `.protocol.http.servers` collection at the root of the code model, that is the colllection of all of them.  If they are all the same, there will be only a single entry.

example : https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/outputs/custom-baseUrl-more-options/code-model-v4.yaml#L177

``` yaml
      protocol: !<!Protocols> 
        http: !<!HttpRequest> 
          path: '/customuri/{subscriptionId}/{keyName}'
          method: get
          servers:
          - !<!HttpServer> &ref_2
            url: '{vault}{secret}{dnsSuffix}'
            variables:
            - !<!ServerVariable> 
              $key: vault
              description: 'The vault name, e.g. https://myvault'
              default: ''
              language:
                default:
                  name: vault
                  description: 'The vault name, e.g. https://myvault'
            - !<!ServerVariable> 
              $key: secret
              description: Secret value.
              default: ''
              language:
                default:
                  name: secret
                  description: Secret value.
            - !<!ServerVariable> 
              $key: dnsSuffix
              description: A string value that is used as a global part of the parameterized host. Default value 'host'.
              default: host
              language:
                default:
                  name: dnsSuffix
                  description: A string value that is used as a global part of the parameterized host. Default value 'host'.
            language:
              default:
                name: server-name
                description: MISSING-SERVER-DESCRIPTION
```
